// lib/strings.js
// Bilingual (English / 简体中文) translation table for all extension UI pages.

export const STRINGS = {
  en: {
    // ---- shared / language switch ----
    "_lang_en": "EN",
    "_lang_zh": "中文",

    // ---- options page ----
    "opt.subtitle": "Configure search engines and extraction behavior. Pure browser extension, no setup required.",
    "opt.openConsole": "Open MCP Console",
    "opt.behaviorTitle": "Behavior",
    "opt.tabLifecycle": "Tab lifecycle after extraction",
    "opt.tabClose": "Close tab (recommended)",
    "opt.tabKeep": "Keep tab open",
    "opt.maxResults": "Max results per search",
    "opt.pageTimeout": "Page load timeout (ms)",
    "opt.save": "Save",
    "opt.enginesTitle": "Search engines",
    "opt.addEngine": "+ Add engine",
    "opt.enginesHint": "Use <code>{query}</code> as the query placeholder in the URL template.",
    "opt.resetEngines": "Reset to defaults",
    "opt.saveEngines": "Save engines",
    "opt.modalAddTitle": "Add engine",
    "opt.modalEditTitle": "Edit engine",
    "opt.fieldName": "Name",
    "opt.fieldUrl": "URL template",
    "opt.fieldUrlHint": "(must contain {query})",
    "opt.fieldResult": "Result selector",
    "opt.fieldResultHint": "(CSS)",
    "opt.fieldLink": "Link selector",
    "opt.fieldTitle": "Title selector",
    "opt.fieldSnippet": "Snippet selector",
    "opt.fieldEnabled": "Enabled",
    "opt.cancel": "Cancel",
    "opt.modalSave": "Save",
    "opt.edit": "Edit",
    "opt.delete": "Delete",
    "opt.noEngines": "No engines configured. Click \"+ Add engine\".",
    "opt.saved": "Saved",
    "opt.engineSaved": "Engine saved (click \"Save engines\" to persist)",
    "opt.enginesSaved": "Engines saved",
    "opt.enginesReset": "Engines reset to defaults",
    "opt.deleted": "Deleted (click \"Save engines\" to persist)",
    "opt.nameRequired": "name is required",
    "opt.urlRequired": "urlTemplate is required",
    "opt.urlPlaceholder": "urlTemplate must contain {query} placeholder",
    "opt.invalidArgs": "Invalid JSON arguments: ",

    // ---- options page: native host bridge ----
    "opt.bridgeTitle": "Native host (desktop MCP clients)",
    "opt.bridgeHint": "Run the bundled Node.js host to expose the extension on a local port. Desktop MCP clients (Claude Desktop, Cursor, etc.) connect to this URL.",
    "opt.bridgeEnabled": "Auto-connect on startup",
    "opt.bridgeHost": "Host",
    "opt.bridgePort": "Port",
    "opt.bridgeTransport": "Transport",
    "opt.bridgeStatus": "Bridge status",
    "opt.bridgeConnected": "Connected",
    "opt.bridgeDisconnected": "Disconnected",
    "opt.bridgeReconnect": "Reconnect",
    "opt.bridgeDisconnect": "Disconnect",
    "opt.bridgeConnect": "Connect",
    "opt.bridgeEndpoints": "Client endpoints",
    "opt.bridgeStreamableHttp": "Streamable HTTP",
    "opt.bridgeSse": "Legacy SSE",
    "opt.bridgeHealth": "Health check",
    "opt.bridgeCopy": "Copy",
    "opt.bridgeCopied": "Copied",
    "opt.bridgeInstallHint": "Not connected? Install the native host first: open native-host/ and run <code>node install_host.mjs --extension-id &lt;YOUR_EXTENSION_ID&gt;</code>",
    "opt.bridgeAttempting": "Attempting to connect…",
    "opt.bridgeError": "Error: ",
    "opt.bridgeAttempts": "Reconnect attempts: ",

    // ---- popup page ----
    "pop.title": "MCP-Browser-Bridge",
    "pop.active": "Active",
    "pop.tools": "tools",
    "pop.console": "MCP Console",
    "pop.settings": "Settings",
    "pop.quickTest": "Quick test",
    "pop.searchQuery": "Search query…",
    "pop.search": "Search",
    "pop.bridge": "Bridge",
    "pop.bridgeOn": "Host: connected",
    "pop.bridgeOff": "Host: off",

    // ---- mcp console page ----
    "mcp.title": "MCP Console",
    "mcp.subtitle": "Invoke any tool directly, or connect an external MCP client using the extension ID below.",
    "mcp.idPill": "Extension ID: …",
    "mcp.extIdTitle": "Extension ID",
    "mcp.extIdHint": "Web-based MCP clients call <code>chrome.runtime.sendMessage(EXTENSION_ID, { type: \"mcp\", payload: &lt;json-rpc&gt; }, callback)</code> to invoke tools. Copy this ID into your client config.",
    "mcp.copy": "Copy",
    "mcp.copied": "Extension ID copied",
    "mcp.copyFailed": "Copy failed: ",
    "mcp.toolsTitle": "Tools",
    "mcp.refresh": "Refresh",
    "mcp.args": "Arguments (JSON)",
    "mcp.call": "Call tool",
    "mcp.clear": "Clear",
    "mcp.calling": "Calling {name}…",
    "mcp.rawTitle": "Raw JSON-RPC",
    "mcp.rawHint": "Send an arbitrary MCP / JSON-RPC 2.0 request.",
    "mcp.request": "Request",
    "mcp.send": "Send",
    "mcp.sending": "Sending…",
    "mcp.emptyReq": "Empty request",
    "mcp.invalidJson": "Invalid JSON: ",
    "mcp.invalidArgsJson": "Invalid JSON arguments: ",
    "mcp.snippetTitle": "Sample client snippet",
    "mcp.notifAccepted": "(notification accepted, no response)",
    "mcp.noResponse": "no response",
    "mcp.error": "Error: ",
    "mcp.failedLoadTools": "Failed to load tools",
    "mcp.bridgeCard": "Native host bridge",
    "mcp.bridgeHint": "Desktop MCP clients connect to the local URL below. The host is a single Node.js file (no Python) bundled in native-host/.",
    "mcp.bridgeStatus": "Status",
    "mcp.bridgeConnected": "Connected",
    "mcp.bridgeDisconnected": "Disconnected",
    "mcp.bridgeEndpoints": "Endpoints",
    "mcp.bridgeCopy": "Copy",
    "mcp.bridgeCopied": "Copied",
    "mcp.bridgeRefresh": "Refresh",
  },
  zh: {
    // ---- shared / language switch ----
    "_lang_en": "EN",
    "_lang_zh": "中文",

    // ---- options page ----
    "opt.subtitle": "配置搜索引擎与提取行为。纯浏览器扩展,无需任何配置。",
    "opt.openConsole": "打开 MCP 控制台",
    "opt.behaviorTitle": "行为",
    "opt.tabLifecycle": "提取后标签页处理",
    "opt.tabClose": "关闭标签页(推荐)",
    "opt.tabKeep": "保留标签页",
    "opt.maxResults": "每次搜索最大结果数",
    "opt.pageTimeout": "页面加载超时(ms)",
    "opt.save": "保存",
    "opt.enginesTitle": "搜索引擎",
    "opt.addEngine": "+ 添加引擎",
    "opt.enginesHint": "URL 模板中用 <code>{query}</code> 作为查询占位符。",
    "opt.resetEngines": "恢复默认",
    "opt.saveEngines": "保存引擎",
    "opt.modalAddTitle": "添加引擎",
    "opt.modalEditTitle": "编辑引擎",
    "opt.fieldName": "名称",
    "opt.fieldUrl": "URL 模板",
    "opt.fieldUrlHint": "(必须包含 {query})",
    "opt.fieldResult": "结果选择器",
    "opt.fieldResultHint": "(CSS)",
    "opt.fieldLink": "链接选择器",
    "opt.fieldTitle": "标题选择器",
    "opt.fieldSnippet": "摘要选择器",
    "opt.fieldEnabled": "启用",
    "opt.cancel": "取消",
    "opt.modalSave": "保存",
    "opt.edit": "编辑",
    "opt.delete": "删除",
    "opt.noEngines": "尚未配置引擎,点击「+ 添加引擎」。",
    "opt.saved": "已保存",
    "opt.engineSaved": "引擎已保存(点击「保存引擎」生效)",
    "opt.enginesSaved": "引擎已保存",
    "opt.enginesReset": "引擎已恢复默认",
    "opt.deleted": "已删除(点击「保存引擎」生效)",
    "opt.nameRequired": "名称为必填项",
    "opt.urlRequired": "URL 模板为必填项",
    "opt.urlPlaceholder": "URL 模板必须包含 {query} 占位符",
    "opt.invalidArgs": "JSON 参数无效:",

    // ---- options page: native host bridge ----
    "opt.bridgeTitle": "原生宿主(桌面端 MCP 客户端)",
    "opt.bridgeHint": "运行自带的 Node.js 宿主,把扩展暴露到本地端口。桌面端 MCP 客户端(Claude Desktop、Cursor 等)通过此 URL 连接。",
    "opt.bridgeEnabled": "启动时自动连接",
    "opt.bridgeHost": "主机",
    "opt.bridgePort": "端口",
    "opt.bridgeTransport": "传输协议",
    "opt.bridgeStatus": "桥接状态",
    "opt.bridgeConnected": "已连接",
    "opt.bridgeDisconnected": "未连接",
    "opt.bridgeReconnect": "重新连接",
    "opt.bridgeDisconnect": "断开",
    "opt.bridgeConnect": "连接",
    "opt.bridgeEndpoints": "客户端连接地址",
    "opt.bridgeStreamableHttp": "Streamable HTTP",
    "opt.bridgeSse": "旧版 SSE",
    "opt.bridgeHealth": "健康检查",
    "opt.bridgeCopy": "复制",
    "opt.bridgeCopied": "已复制",
    "opt.bridgeInstallHint": "连不上?请先安装原生宿主:打开 native-host/ 目录,运行 <code>node install_host.mjs --extension-id &lt;你的扩展ID&gt;</code>",
    "opt.bridgeAttempting": "正在尝试连接…",
    "opt.bridgeError": "错误:",
    "opt.bridgeAttempts": "重连次数:",

    // ---- popup page ----
    "pop.title": "MCP-Browser-Bridge",
    "pop.active": "运行中",
    "pop.tools": "个工具",
    "pop.console": "MCP 控制台",
    "pop.settings": "设置",
    "pop.quickTest": "快速测试",
    "pop.searchQuery": "搜索内容…",
    "pop.search": "搜索",
    "pop.bridge": "桥接",
    "pop.bridgeOn": "宿主:已连接",
    "pop.bridgeOff": "宿主:未连接",

    // ---- mcp console page ----
    "mcp.title": "MCP 控制台",
    "mcp.subtitle": "直接调用任意工具,或使用下方的扩展 ID 连接外部 MCP 客户端。",
    "mcp.idPill": "扩展 ID:…",
    "mcp.extIdTitle": "扩展 ID",
    "mcp.extIdHint": "网页端 MCP 客户端通过 <code>chrome.runtime.sendMessage(EXTENSION_ID, { type: \"mcp\", payload: &lt;json-rpc&gt; }, callback)</code> 调用工具。把此 ID 复制到你的客户端配置中。",
    "mcp.copy": "复制",
    "mcp.copied": "扩展 ID 已复制",
    "mcp.copyFailed": "复制失败:",
    "mcp.toolsTitle": "工具",
    "mcp.refresh": "刷新",
    "mcp.args": "参数(JSON)",
    "mcp.call": "调用工具",
    "mcp.clear": "清空",
    "mcp.calling": "正在调用 {name}…",
    "mcp.rawTitle": "原始 JSON-RPC",
    "mcp.rawHint": "发送任意 MCP / JSON-RPC 2.0 请求。",
    "mcp.request": "请求",
    "mcp.send": "发送",
    "mcp.sending": "发送中…",
    "mcp.emptyReq": "请求为空",
    "mcp.invalidJson": "JSON 无效:",
    "mcp.invalidArgsJson": "JSON 参数无效:",
    "mcp.snippetTitle": "客户端示例",
    "mcp.notifAccepted": "(通知已接受,无响应)",
    "mcp.noResponse": "无响应",
    "mcp.error": "错误:",
    "mcp.failedLoadTools": "工具列表加载失败",
    "mcp.bridgeCard": "原生宿主桥接",
    "mcp.bridgeHint": "桌面端 MCP 客户端通过下方的本地 URL 连接。宿主是单个 Node.js 文件(无 Python),位于 native-host/ 目录。",
    "mcp.bridgeStatus": "状态",
    "mcp.bridgeConnected": "已连接",
    "mcp.bridgeDisconnected": "未连接",
    "mcp.bridgeEndpoints": "连接地址",
    "mcp.bridgeCopy": "复制",
    "mcp.bridgeCopied": "已复制",
    "mcp.bridgeRefresh": "刷新",
  },
};
